### ISSUE TITLE
005_kolla_deploy.sh failed during execution

### ISSUE THREAD

**Issue by davidhui-ampere** [AmpereComputing/openstack-kolla-ampere-aio-scripts#1]
While running script 005_kolla_deploy.sh, system fails with the following error (see error message below). Also log file from 004_kolla_pre_deploy (just in case if it helps)
[004_kolla_pre_deploy.log](https://github.com/AmpereComputing/openstack-kolla-ampere-aio-scripts/files/3948189/004_kolla_pre_deploy.log)

**Error Message while running 005_Kolla_deploy.sh**

TASK [common : Ensure fluentd image is present for label check] ********************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "msg": "'Traceback (most recent call last):\\n  File \"/usr/local/lib/python3.7/dist-packages/docker/api/client.py\", line 261, in _raise_for_status\\n    response.raise_for_status()\\n  File \"/usr/lib/python3/dist-packages/requests/models.py\", line 940, in raise_for_status\\n    raise HTTPError(http_error_msg, response=self)\\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.40/images/create?tag=8.1.0&fromImage=kolla%2Fdebian-source-fluentd\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/tmp/ansible_kolla_docker_payload_ee6f_efh/ansible_kolla_docker_payload.zip/ansible/modules/kolla_docker.py\", line 1024, in main\\n  File \"/tmp/ansible_kolla_docker_payload_ee6f_efh/ansible_kolla_docker_payload.zip/ansible/modules/kolla_docker.py\", line 904, in ensure_image\\n  File \"/tmp/ansible_kolla_docker_payload_ee6f_efh/ansible_kolla_docker_payload.zip/ansible/modules/kolla_docker.py\", line 571, in pull_image\\n  File \"/usr/local/lib/python3.7/dist-packages/docker/api/image.py\", line 415, in pull\\n    self._raise_for_status(response)\\n  File \"/usr/local/lib/python3.7/dist-packages/docker/api/client.py\", line 263, in _raise_for_status\\n    raise create_api_error_from_http_exception(e)\\n  File \"/usr/local/lib/python3.7/dist-packages/docker/errors.py\", line 31, in create_api_error_from_http_exception\\n    raise cls(e, response=response, explanation=explanation)\\ndocker.errors.NotFound: 404 Client Error: Not Found (\"manifest for kolla/debian-source-fluentd:8.1.0 not found: manifest unknown: manifest unknown\")\\n'"}

PLAY RECAP *************************************************************************************************************************************************************************************************
localhost                  : ok=9    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

Command failed ansible-playbook -i /usr/local/share/kolla-ansible/ansible/inventory/all-in-one -e @/etc/kolla/globals.yml -e @/etc/kolla/passwords.yml -e CONFIG_DIR=/etc/kolla  -e kolla_action=deploy /usr/local/share/kolla-ansible/ansible/site.yml

**Comment by ppouliot** [comment]
It can't find the image.  You sure they were there and were finished building from the previous step?

**Comment by ppouliot** [comment]
Issue resolved by moving to correct version of OpenStack.  pull request made to fix issue.
